<script lang="ts" setup>
import themePkg from '../../packages/valaxy-theme-yun/package.json'
import valaxyPkg from '../../packages/valaxy/package.json'
import startupOutput from '../generated/startup-output.txt?raw'

// The transcript is generated by pnpm test:onboarding; only its presentation is
// defined here. Package versions also stay current between acceptance runs.
const output = startupOutput
  .replaceAll('{{valaxyVersion}}', `v${valaxyPkg.version}`)
  .replaceAll('{{themeVersion}}', `v${themePkg.version}`)

const tokens = output.split(/(✔|v\d[^\s)]*|https?:\/\/\S+|\/path\/to\/\S+|userValaxyConfig|siteConfig)/g).map((text) => {
  let color = ''
  if (text === '✔')
    color = 'text-green'
  else if (/^v\d/.test(text))
    color = 'text-blue'
  else if (/^https?:|^(?:userValaxyConfig|siteConfig)$/.test(text))
    color = 'text-cyan'
  else if (text.startsWith('/path/to/'))
    color = 'opacity-70'
  return { text, color }
})
</script>

<template>
  <div class="p-4" text="white sm" bg="dark" rounded-lg>
    <pre class="overflow-auto"><span v-for="(token, index) in tokens" :key="index" :class="token.color">{{ token.text }}</span></pre>
  </div>
</template>
