// import { loadConfig } from 'c12'
import path from 'path'
import fs from 'fs-extra'
import defu from 'defu'
import { ensureSuffix } from '@antfu/utils'
import { normalizePath } from 'vite'
import { loadConfig } from 'unconfig'
import type { VitePluginConfig as UnoCssConfig } from 'unocss/vite'
import type { Awaitable } from '@antfu/utils'
import jiti from 'jiti'
import type { UserConfig, ValaxySiteConfig } from '../types'
import type { ResolvedValaxyOptions, ThemeSetup, ValaxyConfig, ValaxyEntryOptions } from './options'
import { getThemeRoot } from './utils/theme'
/**
 * Type site helper
 */
export function defineSite<ThemeConfig>(config: UserConfig<ThemeConfig>) {
  return config
}

/**
 * Type site helper for custom theme site
 */
export function defineSiteWithTheme<ThemeConfig>(
  config: UserConfig<ThemeConfig>,
) {
  return config
}

export type ValaxyConfigExport<T = Record<string, any>> = ValaxyConfig | Promise<ValaxyConfig> | ValaxyConfigFn<T>
export type ValaxyConfigFn<T> = (options: ResolvedValaxyOptions<T>) => ValaxyConfig | Promise<ValaxyConfig>
/**
 * Type valaxy config helper
 */
export function defineConfig<ThemeConfig>(config: ValaxyConfigExport<ThemeConfig>) {
  return config
}

const defaultSiteConfig: ValaxySiteConfig = {
  mode: 'auto',
  url: '/',
  lang: 'en',
  title: 'Valaxy Blog',
  description: 'A blog generated by Valaxy.',
  subtitle: 'Next Generation Static Blog Framework.',
  author: {
    avatar: 'https://www.yunyoujun.cn/images/avatar.jpg',
    email: 'me@yunyoujun.cn',
    link: 'https://www.yunyoujun.cn',
    name: 'YunYouJun',
    status: {
      emoji: '😊',
      message: 'All at sea.',
    },
  },
  favicon: '/favicon.svg',
  feed: {
    name: '',
    favicon: '/favicon.svg',
  },
  social: [],

  date: {
    format: '',
  },
  lastUpdated: true,

  license: {
    enabled: true,
    language: '',
    type: 'by-nc-sa',
  },

  sponsor: {
    enable: true,
    title: '我很可爱，请给我钱',
    methods: [],
  },

  search: {
    enable: false,
    algolia: {
      enable: false,
      appId: '',
      apiKey: '',
      indexName: '',
    },
  },

  comment: {
    enable: false,
    waline: {
      enable: false,
      serverURL: '',
    },
    twikoo: {
      enable: false,
      envId: 'https://twikoo.vercel.app',
    },
  },

  cdn: {
    prefix: 'https://npm.elemecdn.com/',
  },

  features: {
    katex: true,
  },

  theme: 'yun',
  themeConfig: {
    pkg: {
      name: '',
      version: '',
    },
  },

  // markdown: {
  //   excerpt: '<!-- more -->',
  // },
}

// for user config
export async function resolveSiteConfig(options: ValaxyEntryOptions = {}) {
  // c12 merge array twice, so i deprecated it
  // const { config, configFile } = await loadConfig<ValaxySiteConfig>({
  //   name: 'valaxy',
  //   defaults: defaultSiteConfig,
  // })

  const { config: userConfig, sources } = await loadConfig<ValaxySiteConfig>({
    sources: [
      {
        files: 'site.config',
        extensions: ['ts', 'js', 'mjs', 'cjs', 'json'],
      },
    ],
    merge: false,
  })

  const configFile = normalizePath(sources[0] || '')

  const config = defu(userConfig, defaultSiteConfig)
  // ensure suffix for cdn prefix
  config.cdn.prefix = ensureSuffix('/', config.cdn.prefix)

  const theme = options.theme || config.theme || 'yun'
  let themeSetup: ThemeSetup = {}

  try {
    const themeEntry = path.resolve(getThemeRoot(theme), 'node/index.ts')
    if (!(await fs.pathExists(themeEntry)))
      throw new Error('theme entry not found')

    themeSetup = jiti(__filename)(themeEntry)
    config.themeConfig = defu(config.themeConfig, themeSetup.defaultThemeConfig || {})
  }
  catch (e) {
    console.error(e)
    console.error(`valaxy-theme-${theme} doesn't have default config`)
  }

  try {
    const pkg = fs.readFileSync(require.resolve(`valaxy-theme-${theme}/package.json`), 'utf-8')
    config.themeConfig.pkg = JSON.parse(pkg)
  }
  catch (e) {
    console.error(`valaxy-theme-${theme} doesn't have package.json`)
  }

  config.url = ensureSuffix('/', config.url)

  return {
    config,
    configFile,
    theme,
    themeSetup,
  }
}

export type UnoSetup = () => Awaitable<Partial<UnoCssConfig> | undefined>

export function defineUnoSetup(fn: UnoSetup) {
  return fn
}
