packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts
catalog:
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.35
  '@iconify-json/vscode-icons': ^1.2.21
  '@unhead/addons': ^2.0.10
  '@unhead/schema-org': ^2.0.10
  '@unhead/vue': ^2.0.10
  consola: ^3.4.2
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unhead: ^2.0.10
  vite: ^6.3.5
  vue-i18n: ^11.1.4
  zx: ^8.5.4
onlyBuiltDependencies:
  - vue-demi
