/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/_drafts/README': RouteRecordInfo<'/_drafts/README', '/_drafts/README', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/daily': RouteRecordInfo<'/albums/daily', '/albums/daily', Record<never, never>, Record<never, never>>,
    '/albums/miracle': RouteRecordInfo<'/albums/miracle', '/albums/miracle', Record<never, never>, Record<never, never>>,
    '/albums/sunset': RouteRecordInfo<'/albums/sunset', '/albums/sunset', Record<never, never>, Record<never, never>>,
    '/albums/young': RouteRecordInfo<'/albums/young', '/albums/young', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/bangumi/': RouteRecordInfo<'/bangumi/', '/bangumi', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/collections/': RouteRecordInfo<'/collections/', '/collections', Record<never, never>, Record<never, never>>,
    '/collections/hamster/': RouteRecordInfo<'/collections/hamster/', '/collections/hamster', Record<never, never>, Record<never, never>>,
    '/collections/hamster/1': RouteRecordInfo<'/collections/hamster/1', '/collections/hamster/1', Record<never, never>, Record<never, never>>,
    '/collections/hamster/2': RouteRecordInfo<'/collections/hamster/2', '/collections/hamster/2', Record<never, never>, Record<never, never>>,
    '/collections/hamster/3': RouteRecordInfo<'/collections/hamster/3', '/collections/hamster/3', Record<never, never>, Record<never, never>>,
    '/collections/hamster/dim-star-sky': RouteRecordInfo<'/collections/hamster/dim-star-sky', '/collections/hamster/dim-star-sky', Record<never, never>, Record<never, never>>,
    '/collections/hamster/hamsters-evolve-today': RouteRecordInfo<'/collections/hamster/hamsters-evolve-today', '/collections/hamster/hamsters-evolve-today', Record<never, never>, Record<never, never>>,
    '/collections/hamster/meeting': RouteRecordInfo<'/collections/hamster/meeting', '/collections/hamster/meeting', Record<never, never>, Record<never, never>>,
    '/collections/hamster/our-journey-is-the-stars-and-sea': RouteRecordInfo<'/collections/hamster/our-journey-is-the-stars-and-sea', '/collections/hamster/our-journey-is-the-stars-and-sea', Record<never, never>, Record<never, never>>,
    '/collections/hamster/the-duelist-romance': RouteRecordInfo<'/collections/hamster/the-duelist-romance', '/collections/hamster/the-duelist-romance', Record<never, never>, Record<never, never>>,
    '/collections/hamster/the-lizard-king': RouteRecordInfo<'/collections/hamster/the-lizard-king', '/collections/hamster/the-lizard-king', Record<never, never>, Record<never, never>>,
    '/collections/hamster/the-third-kind': RouteRecordInfo<'/collections/hamster/the-third-kind', '/collections/hamster/the-third-kind', Record<never, never>, Record<never, never>>,
    '/collections/hamster/they-are-the-gods': RouteRecordInfo<'/collections/hamster/they-are-the-gods', '/collections/hamster/they-are-the-gods', Record<never, never>, Record<never, never>>,
    '/collections/hamster/to-be-or-not-to-be': RouteRecordInfo<'/collections/hamster/to-be-or-not-to-be', '/collections/hamster/to-be-or-not-to-be', Record<never, never>, Record<never, never>>,
    '/collections/love-and-peace/': RouteRecordInfo<'/collections/love-and-peace/', '/collections/love-and-peace', Record<never, never>, Record<never, never>>,
    '/collections/love-and-peace/1': RouteRecordInfo<'/collections/love-and-peace/1', '/collections/love-and-peace/1', Record<never, never>, Record<never, never>>,
    '/collections/love-and-peace/2': RouteRecordInfo<'/collections/love-and-peace/2', '/collections/love-and-peace/2', Record<never, never>, Record<never, never>>,
    '/collections/love-and-peace/3': RouteRecordInfo<'/collections/love-and-peace/3', '/collections/love-and-peace/3', Record<never, never>, Record<never, never>>,
    '/collections/README': RouteRecordInfo<'/collections/README', '/collections/README', Record<never, never>, Record<never, never>>,
    '/examples/addons/components': RouteRecordInfo<'/examples/addons/components', '/examples/addons/components', Record<never, never>, Record<never, never>>,
    '/examples/code-height-limit': RouteRecordInfo<'/examples/code-height-limit', '/examples/code-height-limit', Record<never, never>, Record<never, never>>,
    '/examples/custom-components': RouteRecordInfo<'/examples/custom-components', '/examples/custom-components', Record<never, never>, Record<never, never>>,
    '/examples/sites': RouteRecordInfo<'/examples/sites', '/examples/sites', Record<never, never>, Record<never, never>>,
    '/examples/without-aside': RouteRecordInfo<'/examples/without-aside', '/examples/without-aside', Record<never, never>, Record<never, never>>,
    '/examples/without-sidebar': RouteRecordInfo<'/examples/without-sidebar', '/examples/without-sidebar', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/abbrlink': RouteRecordInfo<'/posts/abbrlink', '/posts/abbrlink', Record<never, never>, Record<never, never>>,
    '/posts/about': RouteRecordInfo<'/posts/about', '/posts/about', Record<never, never>, Record<never, never>>,
    '/posts/aplayer': RouteRecordInfo<'/posts/aplayer', '/posts/aplayer', Record<never, never>, Record<never, never>>,
    '/posts/categories-a-b': RouteRecordInfo<'/posts/categories-a-b', '/posts/categories-a-b', Record<never, never>, Record<never, never>>,
    '/posts/categories-a-b-c': RouteRecordInfo<'/posts/categories-a-b-c', '/posts/categories-a-b-c', Record<never, never>, Record<never, never>>,
    '/posts/code': RouteRecordInfo<'/posts/code', '/posts/code', Record<never, never>, Record<never, never>>,
    '/posts/date': RouteRecordInfo<'/posts/date', '/posts/date', Record<never, never>, Record<never, never>>,
    '/posts/design': RouteRecordInfo<'/posts/design', '/posts/design', Record<never, never>, Record<never, never>>,
    '/posts/dev': RouteRecordInfo<'/posts/dev', '/posts/dev', Record<never, never>, Record<never, never>>,
    '/posts/draft': RouteRecordInfo<'/posts/draft', '/posts/draft', Record<never, never>, Record<never, never>>,
    '/posts/encrypted-part-post': RouteRecordInfo<'/posts/encrypted-part-post', '/posts/encrypted-part-post', Record<never, never>, Record<never, never>>,
    '/posts/encrypted-post': RouteRecordInfo<'/posts/encrypted-post', '/posts/encrypted-post', Record<never, never>, Record<never, never>>,
    '/posts/excerpt-type-ai': RouteRecordInfo<'/posts/excerpt-type-ai', '/posts/excerpt-type-ai', Record<never, never>, Record<never, never>>,
    '/posts/excerpt-type-html': RouteRecordInfo<'/posts/excerpt-type-html', '/posts/excerpt-type-html', Record<never, never>, Record<never, never>>,
    '/posts/excerpt-type-md': RouteRecordInfo<'/posts/excerpt-type-md', '/posts/excerpt-type-md', Record<never, never>, Record<never, never>>,
    '/posts/excerpt-type-text': RouteRecordInfo<'/posts/excerpt-type-text', '/posts/excerpt-type-text', Record<never, never>, Record<never, never>>,
    '/posts/framework-and-pages': RouteRecordInfo<'/posts/framework-and-pages', '/posts/framework-and-pages', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hide': RouteRecordInfo<'/posts/hide', '/posts/hide', Record<never, never>, Record<never, never>>,
    '/posts/hide-in-index': RouteRecordInfo<'/posts/hide-in-index', '/posts/hide-in-index', Record<never, never>, Record<never, never>>,
    '/posts/how-to-use-adboard': RouteRecordInfo<'/posts/how-to-use-adboard', '/posts/how-to-use-adboard', Record<never, never>, Record<never, never>>,
    '/posts/katex': RouteRecordInfo<'/posts/katex', '/posts/katex', Record<never, never>, Record<never, never>>,
    '/posts/long-toc': RouteRecordInfo<'/posts/long-toc', '/posts/long-toc', Record<never, never>, Record<never, never>>,
    '/posts/lots-of-images': RouteRecordInfo<'/posts/lots-of-images', '/posts/lots-of-images', Record<never, never>, Record<never, never>>,
    '/posts/markdown': RouteRecordInfo<'/posts/markdown', '/posts/markdown', Record<never, never>, Record<never, never>>,
    '/posts/markdown-styles': RouteRecordInfo<'/posts/markdown-styles', '/posts/markdown-styles', Record<never, never>, Record<never, never>>,
    '/posts/mermaid': RouteRecordInfo<'/posts/mermaid', '/posts/mermaid', Record<never, never>, Record<never, never>>,
    '/posts/nested/a/b/c': RouteRecordInfo<'/posts/nested/a/b/c', '/posts/nested/a/b/c', Record<never, never>, Record<never, never>>,
    '/posts/nested/z/': RouteRecordInfo<'/posts/nested/z/', '/posts/nested/z', Record<never, never>, Record<never, never>>,
    '/posts/post-i18n': RouteRecordInfo<'/posts/post-i18n', '/posts/post-i18n', Record<never, never>, Record<never, never>>,
    '/posts/post-updated': RouteRecordInfo<'/posts/post-updated', '/posts/post-updated', Record<never, never>, Record<never, never>>,
    '/posts/redirect': RouteRecordInfo<'/posts/redirect', '/posts/redirect', Record<never, never>, Record<never, never>>,
    '/posts/test': RouteRecordInfo<'/posts/test', '/posts/test', Record<never, never>, Record<never, never>>,
    '/posts/test-images': RouteRecordInfo<'/posts/test-images', '/posts/test-images', Record<never, never>, Record<never, never>>,
    '/posts/test-tags': RouteRecordInfo<'/posts/test-tags', '/posts/test-tags', Record<never, never>, Record<never, never>>,
    '/posts/type-link-jump': RouteRecordInfo<'/posts/type-link-jump', '/posts/type-link-jump', Record<never, never>, Record<never, never>>,
    '/posts/中文Post测试': RouteRecordInfo<'/posts/中文Post测试', '/posts/中文Post测试', Record<never, never>, Record<never, never>>,
    '/posts/中文分类': RouteRecordInfo<'/posts/中文分类', '/posts/中文分类', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors/': RouteRecordInfo<'/sponsors/', '/sponsors', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/test/custom-blocks': RouteRecordInfo<'/test/custom-blocks', '/test/custom-blocks', Record<never, never>, Record<never, never>>,
    '/test/deadlinks': RouteRecordInfo<'/test/deadlinks', '/test/deadlinks', Record<never, never>, Record<never, never>>,
    '/test/define-basic-loader': RouteRecordInfo<'/test/define-basic-loader', '/test/define-basic-loader', Record<never, never>, Record<never, never>>,
    '/test/footnotes': RouteRecordInfo<'/test/footnotes', '/test/footnotes', Record<never, never>, Record<never, never>>,
    '/test/i18n': RouteRecordInfo<'/test/i18n', '/test/i18n', Record<never, never>, Record<never, never>>,
    '/test/markdown-file-inclusion': RouteRecordInfo<'/test/markdown-file-inclusion', '/test/markdown-file-inclusion', Record<never, never>, Record<never, never>>,
    '/test/special-character': RouteRecordInfo<'/test/special-character', '/test/special-character', Record<never, never>, Record<never, never>>,
    '/test/time_warning': RouteRecordInfo<'/test/time_warning', '/test/time_warning', Record<never, never>, Record<never, never>>,
    '/yun/': RouteRecordInfo<'/yun/', '/yun', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    '../../packages/valaxy-theme-yun/pages/index.vue': {
      routes: '/'
      views: never
    }
    'pages/_drafts/README.md': {
      routes: '/_drafts/README'
      views: never
    }
    '../../packages/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/albums/index.md': {
      routes: '/albums/'
      views: never
    }
    'pages/albums/daily.md': {
      routes: '/albums/daily'
      views: never
    }
    'pages/albums/miracle.md': {
      routes: '/albums/miracle'
      views: never
    }
    'pages/albums/sunset.md': {
      routes: '/albums/sunset'
      views: never
    }
    'pages/albums/young.md': {
      routes: '/albums/young'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/bangumi/index.md': {
      routes: '/bangumi/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/collections/index.md': {
      routes: '/collections/'
      views: never
    }
    'pages/collections/hamster/index.md': {
      routes: '/collections/hamster/'
      views: never
    }
    'pages/collections/hamster/1.md': {
      routes: '/collections/hamster/1'
      views: never
    }
    'pages/collections/hamster/2.md': {
      routes: '/collections/hamster/2'
      views: never
    }
    'pages/collections/hamster/3.md': {
      routes: '/collections/hamster/3'
      views: never
    }
    'pages/collections/hamster/dim-star-sky.md': {
      routes: '/collections/hamster/dim-star-sky'
      views: never
    }
    'pages/collections/hamster/hamsters-evolve-today.md': {
      routes: '/collections/hamster/hamsters-evolve-today'
      views: never
    }
    'pages/collections/hamster/meeting.md': {
      routes: '/collections/hamster/meeting'
      views: never
    }
    'pages/collections/hamster/our-journey-is-the-stars-and-sea.md': {
      routes: '/collections/hamster/our-journey-is-the-stars-and-sea'
      views: never
    }
    'pages/collections/hamster/the-duelist-romance.md': {
      routes: '/collections/hamster/the-duelist-romance'
      views: never
    }
    'pages/collections/hamster/the-lizard-king.md': {
      routes: '/collections/hamster/the-lizard-king'
      views: never
    }
    'pages/collections/hamster/the-third-kind.md': {
      routes: '/collections/hamster/the-third-kind'
      views: never
    }
    'pages/collections/hamster/they-are-the-gods.md': {
      routes: '/collections/hamster/they-are-the-gods'
      views: never
    }
    'pages/collections/hamster/to-be-or-not-to-be.md': {
      routes: '/collections/hamster/to-be-or-not-to-be'
      views: never
    }
    'pages/collections/love-and-peace/index.md': {
      routes: '/collections/love-and-peace/'
      views: never
    }
    'pages/collections/love-and-peace/1.md': {
      routes: '/collections/love-and-peace/1'
      views: never
    }
    'pages/collections/love-and-peace/2.md': {
      routes: '/collections/love-and-peace/2'
      views: never
    }
    'pages/collections/love-and-peace/3.md': {
      routes: '/collections/love-and-peace/3'
      views: never
    }
    'pages/collections/README.md': {
      routes: '/collections/README'
      views: never
    }
    'pages/examples/addons/components.md': {
      routes: '/examples/addons/components'
      views: never
    }
    'pages/examples/code-height-limit.md': {
      routes: '/examples/code-height-limit'
      views: never
    }
    'pages/examples/custom-components.md': {
      routes: '/examples/custom-components'
      views: never
    }
    'pages/examples/sites.md': {
      routes: '/examples/sites'
      views: never
    }
    'pages/examples/without-aside.md': {
      routes: '/examples/without-aside'
      views: never
    }
    'pages/examples/without-sidebar.md': {
      routes: '/examples/without-sidebar'
      views: never
    }
    'pages/girls/index.md': {
      routes: '/girls/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'pages/notes/index.md': {
      routes: '/notes/'
      views: never
    }
    '../../packages/valaxy-theme-yun/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    '../../packages/valaxy-theme-yun/pages/posts/index.vue': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/abbrlink.md': {
      routes: '/posts/abbrlink'
      views: never
    }
    'pages/posts/about.md': {
      routes: '/posts/about'
      views: never
    }
    'pages/posts/aplayer.md': {
      routes: '/posts/aplayer'
      views: never
    }
    'pages/posts/categories-a-b.md': {
      routes: '/posts/categories-a-b'
      views: never
    }
    'pages/posts/categories-a-b-c.md': {
      routes: '/posts/categories-a-b-c'
      views: never
    }
    'pages/posts/code.md': {
      routes: '/posts/code'
      views: never
    }
    'pages/posts/date.md': {
      routes: '/posts/date'
      views: never
    }
    'pages/posts/design.md': {
      routes: '/posts/design'
      views: never
    }
    'pages/posts/dev.md': {
      routes: '/posts/dev'
      views: never
    }
    'pages/posts/draft.md': {
      routes: '/posts/draft'
      views: never
    }
    'pages/posts/encrypted-part-post.md': {
      routes: '/posts/encrypted-part-post'
      views: never
    }
    'pages/posts/encrypted-post.md': {
      routes: '/posts/encrypted-post'
      views: never
    }
    'pages/posts/excerpt-type-ai.md': {
      routes: '/posts/excerpt-type-ai'
      views: never
    }
    'pages/posts/excerpt-type-html.md': {
      routes: '/posts/excerpt-type-html'
      views: never
    }
    'pages/posts/excerpt-type-md.md': {
      routes: '/posts/excerpt-type-md'
      views: never
    }
    'pages/posts/excerpt-type-text.md': {
      routes: '/posts/excerpt-type-text'
      views: never
    }
    'pages/posts/framework-and-pages.md': {
      routes: '/posts/framework-and-pages'
      views: never
    }
    'pages/posts/hello-valaxy.md': {
      routes: '/posts/hello-valaxy'
      views: never
    }
    'pages/posts/hide.md': {
      routes: '/posts/hide'
      views: never
    }
    'pages/posts/hide-in-index.md': {
      routes: '/posts/hide-in-index'
      views: never
    }
    'pages/posts/how-to-use-adboard.md': {
      routes: '/posts/how-to-use-adboard'
      views: never
    }
    'pages/posts/katex.md': {
      routes: '/posts/katex'
      views: never
    }
    'pages/posts/long-toc.md': {
      routes: '/posts/long-toc'
      views: never
    }
    'pages/posts/lots-of-images.md': {
      routes: '/posts/lots-of-images'
      views: never
    }
    'pages/posts/markdown.md': {
      routes: '/posts/markdown'
      views: never
    }
    'pages/posts/markdown-styles.md': {
      routes: '/posts/markdown-styles'
      views: never
    }
    'pages/posts/mermaid.md': {
      routes: '/posts/mermaid'
      views: never
    }
    'pages/posts/nested/a/b/c.md': {
      routes: '/posts/nested/a/b/c'
      views: never
    }
    'pages/posts/nested/z/index.md': {
      routes: '/posts/nested/z/'
      views: never
    }
    'pages/posts/post-i18n.md': {
      routes: '/posts/post-i18n'
      views: never
    }
    'pages/posts/post-updated.md': {
      routes: '/posts/post-updated'
      views: never
    }
    'pages/posts/redirect.md': {
      routes: '/posts/redirect'
      views: never
    }
    'pages/posts/test.md': {
      routes: '/posts/test'
      views: never
    }
    'pages/posts/test-images.md': {
      routes: '/posts/test-images'
      views: never
    }
    'pages/posts/test-tags.md': {
      routes: '/posts/test-tags'
      views: never
    }
    'pages/posts/type-link-jump.md': {
      routes: '/posts/type-link-jump'
      views: never
    }
    'pages/posts/中文Post测试.md': {
      routes: '/posts/中文Post测试'
      views: never
    }
    'pages/posts/中文分类.md': {
      routes: '/posts/中文分类'
      views: never
    }
    'pages/projects/index.md': {
      routes: '/projects/'
      views: never
    }
    'pages/sponsors/index.md': {
      routes: '/sponsors/'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
    'pages/test/custom-blocks.md': {
      routes: '/test/custom-blocks'
      views: never
    }
    'pages/test/deadlinks.md': {
      routes: '/test/deadlinks'
      views: never
    }
    'pages/test/define-basic-loader.md': {
      routes: '/test/define-basic-loader'
      views: never
    }
    'pages/test/footnotes.md': {
      routes: '/test/footnotes'
      views: never
    }
    'pages/test/i18n.md': {
      routes: '/test/i18n'
      views: never
    }
    'pages/test/markdown-file-inclusion.md': {
      routes: '/test/markdown-file-inclusion'
      views: never
    }
    'pages/test/special-character.md': {
      routes: '/test/special-character'
      views: never
    }
    'pages/test/time_warning.md': {
      routes: '/test/time_warning'
      views: never
    }
    'pages/yun/index.md': {
      routes: '/yun/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
