import type { VitePluginConfig as UnoCssConfig } from 'unocss/vite'
import type { Awaitable } from '@antfu/utils'
import type { SiteConfig, UserSiteConfig } from '../../types'
import type { UserValaxyNodeConfig, ValaxyNodeConfig } from '../types'

export * from './addon'

/**
 * Type helper for site.config.ts
 * @param config
 * @returns
 */
export function defineSiteConfig(config: UserSiteConfig) {
  return config
}

/**
 * Type helper for valaxy.config.ts
 */
export function defineValaxyConfig<ThemeConfig>(config: UserValaxyNodeConfig<ThemeConfig>) {
  return config
}
export const defineConfig = defineValaxyConfig

export const defaultSiteConfig: SiteConfig = {
  mode: 'auto',
  url: '/',
  lang: 'en',
  title: 'Valaxy Blog',
  description: 'A blog generated by Valaxy.',
  subtitle: 'Next Generation Static Blog Framework.',
  author: {
    // todo valaxy logo
    avatar: 'https://www.yunyoujun.cn/images/avatar.jpg',
    email: 'i@valaxy.site',
    link: 'https://valaxy.site',
    name: 'VALAXY Developer',
    status: {
      emoji: '🌌',
      message: 'The moonlight is beautiful.',
    },
  },
  favicon: '/favicon.svg',
  feed: {
    name: '',
    favicon: '/favicon.svg',
  },
  social: [],

  date: {
    format: '',
  },
  lastUpdated: true,

  license: {
    enabled: true,
    language: '',
    type: 'by-nc-sa',
  },

  sponsor: {
    enable: true,
    description: '这是关于赞助的一些描述',
    methods: [],
  },

  search: {
    enable: false,
    type: 'fuse',
  },

  comment: {
    enable: false,
  },

  cdn: {
    prefix: 'https://unpkg.com/',
  },

  mediumZoom: {
    enable: false,
    selector: '',
    options: {},
  },

  statistics: {
    enable: false,
    readTime: {
      speed: {
        cn: 300,
        en: 100,
      },
    },
  },

  pageSize: 7,

}

export const defaultValaxyConfig: ValaxyNodeConfig = {
  ignoreDeadLinks: true,

  siteConfig: defaultSiteConfig,
  theme: 'yun',
  themeConfig: {
    pkg: {
      name: '',
      version: '',
    },
  },

  // markdown: {
  //   excerpt: '<!-- more -->',
  // },
  runtimeConfig: { addons: {} },

  features: {
    katex: true,
  },

  vite: {
    build: {
      rollupOptions: {
        external: [],
      },
    },
  },
}

export type UnoSetup = () => Awaitable<Partial<UnoCssConfig> | undefined>

export function defineUnoSetup(fn: UnoSetup) {
  return fn
}
