import type { SiteConfig, UserSiteConfig } from '../../types'
import { webcrypto } from 'node:crypto'
import { consola } from 'consola'
import { colors } from 'consola/utils'
import { options as floatingVueOptions } from 'floating-vue'
import { countPerformanceTime } from '../utils/performance'
import { loadConfigFromFile } from './utils'

export const defaultSiteConfig: SiteConfig = {
  mode: 'auto',
  url: '/',
  lang: 'en',
  languages: ['en', 'zh-CN'],
  timezone: '',
  title: 'Valaxy Blog',
  description: 'A blog generated by Valaxy.',
  subtitle: 'Next Generation Static Blog Framework.',
  author: {
    avatar: 'https://valaxy.site/valaxy-logo.png',
    email: 'i@valaxy.site',
    link: 'https://valaxy.site',
    name: 'VALAXY Developer',
    status: {
      emoji: '🌌',
      message: 'The moonlight is beautiful.',
    },
  },
  favicon: '/favicon.svg',
  feed: {
    name: '',
    favicon: '/favicon.svg',
  },
  social: [],

  orderBy: 'date',
  lastUpdated: false,

  license: {
    enabled: true,
    language: '',
    type: 'by-nc-sa',
  },

  sponsor: {
    enable: true,
    description: '这是关于赞助的一些描述',
    methods: [],
  },

  search: {
    enable: false,
    provider: 'fuse',
  },
  fuse: {
    dataPath: 'valaxy-fuse-list.json',
    options: {
      keys: [],
    },
  },

  comment: {
    enable: false,
  },

  excerpt: {
    type: 'html',
    auto: false,
    length: 200,
  },

  frontmatter: {
    time_warning: 180 * 24 * 60 * 60 * 1000,
  },

  cdn: {
    prefix: 'https://unpkg.com/',
  },

  mediumZoom: {
    enable: false,
    selector: '',
    options: {},
  },

  vanillaLazyload: {
    enable: false,
    options: {},
  },

  floatingVue: floatingVueOptions,

  footnote: {
    preview: 'reka',
  },

  statistics: {
    enable: false,
    readTime: {
      speed: {
        cn: 300,
        en: 100,
      },
    },
  },

  pageSize: 7,

  encrypt: {
    enable: false,
    algorithm: 'AES-CBC',
    salt: webcrypto.getRandomValues(new Uint8Array(16)),
    iv: webcrypto.getRandomValues(new Uint8Array(16)),
  },

  redirects: {
    useVueRouter: true,
    rules: [],
  },

  llms: {
    enable: false,
    fullText: true,
    files: true,
    prompt: '',
    include: ['posts/**/*.md'],
  },
}

/**
 * Type helper for site.config.ts
 * @param config
 */
export function defineSiteConfig(config: UserSiteConfig) {
  return config
}

/** Resolve before merging defaults so explicit legacy settings stay effective. */
export function resolveFootnoteConfig(config: UserSiteConfig = {}): SiteConfig['footnote'] {
  const preview = config.footnote?.preview
  if (config.floatingVue != null) {
    consola.warn(preview === 'reka'
      ? '[Valaxy] siteConfig.floatingVue only configures legacy Floating Vue APIs; Reka footnotes use .va-footnote-popover styles.'
      : '[Valaxy] siteConfig.floatingVue is deprecated for footnotes. Keeping the legacy preview; migrate with footnote: { preview: \'reka\' }. See https://valaxy.site/guide/markdown#footnote-preview')
  }
  return { preview: preview ?? (config.floatingVue != null ? 'floating-vue' : 'reka') }
}

/**
 * resolve valaxy config from special root
 */
export async function resolveSiteConfigFromRoot(root: string) {
  return loadConfigFromFile<UserSiteConfig>('site', {
    cwd: root,
  })
}

/**
 * resolve site.config.ts and merge with default
 * @param root
 */
export async function resolveSiteConfig(root: string) {
  const endCount = countPerformanceTime()
  const { config: userSiteConfig, configFile: siteConfigFile } = await resolveSiteConfigFromRoot(root)
  const duration = endCount()

  if (userSiteConfig && siteConfigFile)
    consola.success(`Resolve ${colors.cyan('siteConfig')} from ${colors.dim(siteConfigFile)} ${colors.yellow(duration)}`)

  return {
    siteConfig: userSiteConfig,
    siteConfigFile,
  }
}
