<script setup lang="ts">
import { useCodeHighlight } from '../composables/code-highlight'

const props = withDefaults(defineProps<{
  code: string
  lang?: string
}>(), { lang: 'text' })

const html = useCodeHighlight(() => props.code, () => props.lang)
</script>

<template>
  <div class="vd-code">
    <!-- Only HTML escaped and generated by the official Shiki service. -->
    <div v-if="html" v-html="html" />
    <pre v-else tabindex="0"><code>{{ code }}</code></pre>
  </div>
</template>

<style scoped>
.vd-code :deep(pre) {
  margin: 0;
  padding: 0 1rem 1rem;
  max-height: 20rem;
  overflow: auto;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  font-size: 0.75rem;
  line-height: 1.625;
  background-color: transparent !important;
}

.vd-code :deep(pre:focus-visible) {
  outline: 2px solid var(--colors-primary-500);
  outline-offset: -2px;
}

html.dark .vd-code :deep(.shiki),
html.dark .vd-code :deep(.shiki span) {
  color: var(--shiki-dark) !important;
  font-style: var(--shiki-dark-font-style, normal) !important;
  font-weight: var(--shiki-dark-font-weight, normal) !important;
  text-decoration: var(--shiki-dark-text-decoration, none) !important;
}
</style>
