import type { ContentItem, ContentLoader, ContentLoaderContext } from 'valaxy'
import type { TypeDocAddonOptions } from './index'
import { execFileSync, spawn } from 'node:child_process'
import { createHash } from 'node:crypto'
import { createRequire } from 'node:module'
import { dirname, relative, resolve, sep } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import fg from 'fast-glob'
import fs from 'fs-extra'
import { minimatch } from 'minimatch'
import { resolveSymbolAnchors } from './links'

interface NavigationItem {
  title: string
  path?: string | null
  children?: NavigationItem[]
}

interface SidebarItem {
  text: string
  link?: string
  collapsed?: boolean
  items?: SidebarItem[]
}

interface Cache {
  key: string
  files: string[]
  items: ContentItem[]
  navigation: NavigationItem[]
  source: { revision: string, dirty: boolean, version?: string }
}

const require = createRequire(import.meta.url)

export function createTypeDocLoader(settings: TypeDocAddonOptions, userRoot: string) {
  const optionsFile = resolve(userRoot, settings.options)
  const routeBase = `/${(settings.routeBase || '/api/').replace(/^\/+|\/+$/g, '')}/`
  if (routeBase.includes('..') || routeBase.includes('\\') || routeBase.includes('#') || routeBase.includes('?'))
    throw new Error('[typedoc] routeBase must be an absolute URL directory without traversal.')
  const watchedRoots = settings.watch.filter(pattern => !pattern.startsWith('!')).map(pattern => resolve(userRoot, pattern.split(/[*?{[]/)[0]))
  let dependencies: string[] = []
  let navigation: NavigationItem[] = []
  let source: Cache['source'] = { revision: 'unversioned', dirty: false }
  let runs = 0

  async function sourceFiles() {
    const sources = await fg(settings.watch, { cwd: userRoot, absolute: true, onlyFiles: true, ignore: ['**/.valaxy/**', '**/dist/**'] })
    return [...new Set([optionsFile, ...sources, ...dependencies])].sort()
  }

  async function fingerprint(files: string[]) {
    const hash = createHash('sha256').update(JSON.stringify({ schema: 8, settings }))
    for (const pkg of ['valaxy-addon-typedoc', 'typedoc', 'typedoc-plugin-markdown', 'typescript']) {
      let directory = dirname(require.resolve(pkg))
      while (directory !== dirname(directory)) {
        const metadata = await fs.readJson(resolve(directory, 'package.json')).catch(() => undefined)
        if (metadata?.name === pkg) {
          hash.update(JSON.stringify(metadata))
          break
        }
        directory = dirname(directory)
      }
    }
    // Source links generated by TypeDoc point at this exact revision.
    try {
      source.revision = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: userRoot, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
      source.dirty = !!execFileSync('git', ['status', '--porcelain'], { cwd: userRoot, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
      hash.update(JSON.stringify({ revision: source.revision, dirty: source.dirty }))
    }
    catch { hash.update('unversioned') }
    for (const file of files) {
      hash.update(file)
      hash.update(await fs.readFile(file).catch(() => 'missing'))
    }
    return hash.digest('hex')
  }

  const toSidebar = (items: NavigationItem[]): SidebarItem[] => items.map(item => ({
    text: item.title,
    ...(item.path ? { link: `${routeBase}${item.path.replace(/(^|\/)index\.md$/, '$1').replace(/\.md(?=#|$)/, '')}` } : {}),
    ...(item.children?.length ? { collapsed: true, items: toSidebar(item.children) } : {}),
  }))

  const loader: ContentLoader & { sourceFiles: typeof sourceFiles, watchPaths: () => Promise<string[]>, isSource: (file: string) => boolean, generationCount: () => number } = {
    name: `typedoc-${routeBase.replaceAll('/', '-')}`,
    strict: true,
    sourceFiles,
    watchPaths: async () => [...new Set([...watchedRoots, ...await sourceFiles()])],
    generationCount: () => runs,
    isSource(file) {
      const path = relative(userRoot, file).replaceAll('\\', '/')
      if (/(?:^|\/)\.valaxy\/|(?:^|\/)dist\//.test(path))
        return false
      const excluded = settings.watch.filter(pattern => pattern.startsWith('!'))
      const included = settings.watch.filter(pattern => !pattern.startsWith('!'))
      return file === optionsFile || dependencies.includes(file)
        || (included.some(pattern => minimatch(path, pattern, { dot: true }))
          && !excluded.some(pattern => minimatch(path, pattern.slice(1), { dot: true })))
    },
    async load(ctx) {
      const cacheRoot = resolve(ctx.cacheDir, loader.name)
      const manifest = resolve(cacheRoot, 'cache.json')
      const previous = await fs.readJson(manifest).catch(() => undefined) as Cache | undefined
      dependencies = previous?.files || []
      const files = await sourceFiles()
      const key = await fingerprint(files)
      if (previous?.key === key && previous.items.length) {
        navigation = previous.navigation
        source = previous.source
        return previous.items
      }

      const started = performance.now()
      const output = resolve(cacheRoot, 'staging')
      await fs.ensureDir(output)
      const resultFile = resolve(cacheRoot, 'worker-result.json')
      runs++
      await new Promise<void>((accept, reject) => {
        const child = spawn(process.execPath, [
          fileURLToPath(new URL('./worker.mjs', import.meta.url)),
          optionsFile,
          output,
          resolve(cacheRoot, 'navigation.json'),
          resultFile,
          routeBase,
        ], { cwd: userRoot, stdio: ['ignore', 'pipe', 'pipe'] })
        let diagnostics = ''
        child.stdout.on('data', chunk => process.stdout.write(chunk))
        child.stderr.on('data', (chunk) => {
          diagnostics = (diagnostics + String(chunk)).slice(-8000)
          process.stderr.write(chunk)
        })
        child.once('error', reject)
        child.once('close', code => code === 0 ? accept() : reject(new Error(`[typedoc] Generation failed (${code}). ${diagnostics}`)))
      })
      const result = await fs.readJson(resultFile) as { files: string[], version?: string }
      dependencies = result.files
      source.version = result.version
      const paths = await fg('**/*.md', { cwd: output })
      if (!paths.length)
        throw new Error('[typedoc] Refusing to publish empty API documentation.')
      const sources = new Map(await Promise.all(paths.map(async page => [page, await fs.readFile(resolve(output, page), 'utf8')] as const)))
      const anchors = new Map([...sources].map(([page, markdown]) => [
        `${routeBase}${page}`,
        new Set([...markdown.matchAll(/<a id="([^"]+)"><\/a>/g)].map(match => match[1])),
      ]))
      const items: ContentItem[] = []
      for (const page of paths.sort()) {
        if (settings.excludeIndex && page === 'index.md')
          continue
        const markdown = resolveSymbolAnchors(sources.get(page)!, anchors)
        const title = markdown.match(/^# (.+?)(?: \{#.*\})?$/m)?.[1] || page
        const revision = `${source.version ? `${source.version} · ` : ''}${source.revision.slice(0, 12)}${source.dirty ? ' (uncommitted changes)' : ''}`
        const body = markdown.replace(/^(# .+\n)/m, `$1\n> Source: ${revision}\n`)
        const canonical = `${routeBase}${page.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '')}`
        const content = `---\ncanonical: ${JSON.stringify(canonical)}\ntitle: ${JSON.stringify(title)}\npageTitle: false\napi: true\napiSource: ${JSON.stringify(source)}\nsharedLocale: true\neditLink: false\nlastUpdated: false\n---\n\n${body}`
        items.push({ path: `${routeBase.slice(1)}${page}`, content })
      }
      if (!items.length)
        throw new Error('[typedoc] Refusing to replace references with an empty page set.')
      navigation = await fs.readJson(resolve(cacheRoot, 'navigation.json'))
      // Include parent project configuration and package metadata in dependency invalidation.
      const checkedDirectories = new Set<string>()
      for (const file of [...dependencies, optionsFile]) {
        let directory = dirname(file)
        while (directory !== dirname(directory) && !checkedDirectories.has(directory)) {
          checkedDirectories.add(directory)
          if (!directory.includes(`${sep}node_modules${sep}`)) {
            for (const name of ['tsconfig.json', 'package.json', 'pnpm-lock.yaml']) {
              const config = resolve(directory, name)
              if (await fs.pathExists(config))
                dependencies.push(config)
            }
          }
          directory = dirname(directory)
        }
      }
      dependencies = [...new Set(dependencies)]
      if (await fingerprint(files) !== key)
        throw new Error('[typedoc] Inputs changed during generation; previous pages were preserved. Retry the build.')
      const finalFiles = await sourceFiles()
      const next: Cache = { key: await fingerprint(finalFiles), files: finalFiles, items, navigation, source }
      await fs.writeJson(`${manifest}.tmp`, next)
      await fs.rename(`${manifest}.tmp`, manifest)
      process.stdout.write(`[typedoc] Generated ${items.length} pages in ${((performance.now() - started) / 1000).toFixed(2)}s\n`)
      return items
    },
    onLoaded(ctx: ContentLoaderContext) {
      const theme = ctx.node.options.config.themeConfig as Record<string, any>
      theme.apiReference = source
      if (settings.sidebar === false)
        return
      const install = (config: Record<string, any>) => {
        const sidebar = config.sidebar
        config.sidebar = { ...(Array.isArray(sidebar) ? { '/': sidebar } : sidebar), [routeBase]: toSidebar(navigation) }
      }
      install(theme)
      for (const locale of Object.values(theme.locales || {}) as Record<string, any>[]) {
        locale.themeConfig ??= {}
        install(locale.themeConfig)
      }
    },
  }
  return loader
}
