// import { loadConfig } from 'c12'
import { loadConfig } from 'unconfig'
import defu from 'defu'
import type { ValaxyConfig } from '../types'
import type { ValaxyEntryOptions } from './options'

// for user config
export async function resolveConfig(options: ValaxyEntryOptions = {}) {
  const defaultValaxyConfig: ValaxyConfig = {
    title: 'Valaxy Blog',
    subtitle: 'Next Generation Static Blog Framework.',
    author: {
      avatar: 'https://cdn.jsdelivr.net/gh/YunYouJun/yun/images/meme/yun-good-with-bg.jpg',
      name: 'YunYouJun',
      status: {
        emoji: '😊',
        message: 'All at sea.',
      },
    },
    social: [],
    description: 'A blog generated by Valaxy.',
    theme: 'yun',
    themeConfig: {},

    unocss: {},
  }
  // c12 merge array twice, so i deprecated it
  // const { config, configFile } = await loadConfig<ValaxyConfig>({
  //   name: 'valaxy',
  //   defaults: defaultValaxyConfig,
  // })

  const { config: userConfig, sources } = await loadConfig<ValaxyConfig>({
    sources: [
      {
        files: 'valaxy.config',
        extensions: ['ts', 'js', 'mjs', 'cjs', 'json'],
      },
    ],
    merge: false,
  })
  const configFile = sources[0]
  const config = defu(userConfig, defaultValaxyConfig)

  const theme = options.theme || config.theme || 'yun'

  try {
    const { defaultThemeConfig } = await import(`valaxy-theme-${theme}`)
    config.themeConfig = defu(config.themeConfig, defaultThemeConfig)
  }
  catch (e) {
    console.error(`valaxy-theme-${theme} doesn't have default config`)
  }

  return {
    config,
    configFile,
    theme,
  }
}
