// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../packages/valaxy-theme-press/layouts/404.vue')['default']
    AppLink: typeof import('./../packages/valaxy/client/components/AppLink.vue')['default']
    Default: typeof import('./../packages/valaxy-theme-press/layouts/default.vue')['default']
    Home: typeof import('./../packages/valaxy-theme-press/layouts/home.vue')['default']
    Layout: typeof import('./../packages/valaxy-theme-press/layouts/layout.vue')['default']
    Post: typeof import('./../packages/valaxy-theme-press/layouts/post.vue')['default']
    PressArticle: typeof import('./../packages/valaxy-theme-press/components/PressArticle.vue')['default']
    PressArticleCard: typeof import('./../packages/valaxy-theme-press/components/PressArticleCard.vue')['default']
    PressAuthor: typeof import('./../packages/valaxy-theme-press/components/PressAuthor.vue')['default']
    PressDate: typeof import('./../packages/valaxy-theme-press/components/PressDate.vue')['default']
    PressHeader: typeof import('./../packages/valaxy-theme-press/components/PressHeader.vue')['default']
    PressNav: typeof import('./../packages/valaxy-theme-press/components/PressNav.vue')['default']
    PressPostList: typeof import('./../packages/valaxy-theme-press/components/PressPostList.vue')['default']
    PressToggleLocale: typeof import('./../packages/valaxy-theme-press/components/PressToggleLocale.vue')['default']
    README: typeof import('./../packages/valaxy/client/layouts/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValaxyCopyright: typeof import('./../packages/valaxy/client/components/ValaxyCopyright.vue')['default']
    ValaxyHamburger: typeof import('./../packages/valaxy/client/components/ValaxyHamburger.vue')['default']
    ValaxyMain: typeof import('./../packages/valaxy-theme-press/components/ValaxyMain.vue')['default']
    ValaxyMd: typeof import('./../packages/valaxy/client/components/ValaxyMd.vue')['default']
    ValaxyOverlay: typeof import('./../packages/valaxy/client/components/ValaxyOverlay.vue')['default']
    ValaxyPagination: typeof import('./../packages/valaxy/client/components/ValaxyPagination.vue')['default']
    ValaxySidebar: typeof import('./../packages/valaxy/client/components/ValaxySidebar.vue')['default']
  }
}
