// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/common/AppLink.vue')['default']
    Counter: typeof import('./../../../../demo/yun/components/Counter.vue')['default']
    CustomComponent: typeof import('./../../../../demo/yun/components/CustomComponent.vue')['default']
    PostList: typeof import('./src/components/common/PostList.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    UpyunSupport: typeof import('./../../../../demo/yun/components/UpyunSupport.vue')['default']
    ValaxyCopyright: typeof import('./src/components/common/ValaxyCopyright.vue')['default']
    ValaxyFooter: typeof import('./src/components/common/ValaxyFooter.vue')['default']
    ValaxyHamburger: typeof import('./src/components/common/ValaxyHamburger.vue')['default']
    ValaxyMd: typeof import('./src/components/common/ValaxyMd.vue')['default']
    ValaxyOverlay: typeof import('./src/components/common/ValaxyOverlay.vue')['default']
    ValaxyRightSidebar: typeof import('./src/components/common/ValaxyRightSidebar.vue')['default']
    ValaxySidebar: typeof import('./src/components/common/ValaxySidebar.vue')['default']
    YunBackToTop: typeof import('./../../../valaxy-theme-yun/src/components/YunBackToTop.vue')['default']
    YunBanner: typeof import('./src/components/YunBanner.vue')['default']
    YunBase: typeof import('./../../../../demo/yun/components/YunBase.vue')['default']
    YunCard: typeof import('./../../../valaxy-theme-yun/src/components/YunCard.vue')['default']
    YunCategories: typeof import('./../../../valaxy-theme-yun/src/components/YunCategories.vue')['default']
    YunCategory: typeof import('./../../../valaxy-theme-yun/src/components/YunCategory.vue')['default']
    YunCloud: typeof import('./../../../valaxy-theme-yun/src/components/YunCloud.vue')['default']
    YunConfig: typeof import('./../../../valaxy-theme-yun/src/components/YunConfig.vue')['default']
    YunGoDown: typeof import('./../../../valaxy-theme-yun/src/components/YunGoDown.vue')['default']
    YunPageHeader: typeof import('./../../../valaxy-theme-yun/src/components/YunPageHeader.vue')['default']
    YunPostCollapse: typeof import('./../../../valaxy-theme-yun/src/components/YunPostCollapse.vue')['default']
    YunPostMeta: typeof import('./../../../valaxy-theme-yun/src/components/YunPostMeta.vue')['default']
    YunPostNav: typeof import('./../../../valaxy-theme-yun/src/components/YunPostNav.vue')['default']
    YunSay: typeof import('./../../../valaxy-theme-yun/src/components/YunSay.vue')['default']
    YunSidebar: typeof import('./../../../valaxy-theme-yun/src/components/YunSidebar.vue')['default']
    YunSidebarLinks: typeof import('./../../../valaxy-theme-yun/src/components/YunSidebarLinks.vue')['default']
    YunSidebarNav: typeof import('./../../../valaxy-theme-yun/src/components/YunSidebarNav.vue')['default']
    YunSocialLinks: typeof import('./../../../valaxy-theme-yun/src/components/YunSocialLinks.vue')['default']
    YunSponsor: typeof import('./../../../valaxy-theme-yun/src/components/YunSponsor.vue')['default']
    YunWaline: typeof import('./../../../valaxy-theme-yun/src/components/YunWaline.vue')['default']
  }
}

export { }
