// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    README: typeof import('./src/components/README.md')['default']
    ValaxyHamburger: typeof import('./src/components/common/ValaxyHamburger.vue')['default']
    ValaxyOverlay: typeof import('./src/components/common/ValaxyOverlay.vue')['default']
    ValaxySidebar: typeof import('./src/components/common/ValaxySidebar.vue')['default']
    YunBanner: typeof import('./src/components/YunBanner.vue')['default']
    YunCloud: typeof import('./../../../theme-yun/src/components/YunCloud.vue')['default']
    YunGoDown: typeof import('./../../../theme-yun/src/components/YunGoDown.vue')['default']
    YunSay: typeof import('./../../../theme-yun/src/components/YunSay.vue')['default']
  }
}

export { }
